import { Inter } from "next/font/google"
import Image from "next/image"
import { Header } from "./Header"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Image src="/img.jpeg" alt="random image" width={250} height={250} />

        {children}
      </body>
    </html>
  )
}
